package:
  name: msmbuilder-dev
  version: "3.5.0.dev0"

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main


requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - mdtraj
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc
    - jinja2


test:
  requires:
    - nose
    - nose-timer
    - munkres
    - numdifftools
    - statsmodels
    - hmmlearn
    - cvxpy # [not win]
  imports:
    - msmbuilder
  commands:
    - msmb -h
    - nosetests msmbuilder -v --with-timer


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'
